# Site settings
title: Taeguk.co.uk
email: dave@taeguk.co.uk
description: Dave Shaw's Development Blog
url: https://taeguk.co.uk
enforce_ssl: taeguk.co.uk 
twitter_username: xdaDaveShaw
github_username:  xdaDaveShaw
stackoverflow_link: users/383710/daveshaw

# Build settings
markdown: kramdown
permalink: /blog/:title/
contenturl: "/blog/Content/"

