# Site settings
title: Taeguk.co.uk
email: dave@taeguk.co.uk
description: Dave Shaw's Development Blog
baseurl: ""
url: http://xdaDaveShaw.github.io
twitter_username: xdaDaveShaw
github_username:  xdaDaveShaw

# Build settings
markdown: kramdown
contenturl: "/content/"
